### ISSUE TITLE
Functions.php

### ISSUE THREAD

**Issue by psychomad** [MrSqar-Ye/BadMod#3]
Hello
I got this on scanning session, any clue? im totally noob on php

_PHP Warning:  fopen(SingleScan/singleSite.txt): failed to open stream: No such file or directory in /bin/badmodF/Functions.php on line 658
PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /bin/badmodF/Functions.php on line 659
PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /bin/badmodF/Functions.php on line 660
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /bin/badmodF/Functions.php on line 661_

**Comment by MrSqar-Ye** [comment]
go to tool folder (BadMod) from terminal and type:
mkdir SingleScan
:"D

**Comment by MrSqar-Ye** [comment]
then try this command : 
sudo mkdir /bin/badmodF/SingleScan

**Comment by psychomad** [comment]
Hello, 
Thanks for answering but everything was already made from app.
The funny thing is: now everything work fine! No clue why, i just update system. as usual
Thanks anyway
