### ISSUE TITLE
permission  denied

### ISSUE THREAD

**Issue by khanjerry** [MrSqar-Ye/BadMod#5]
bin/badbodF/BadMod.php:permission denied 

how to solve this bro

**Comment by Endt4sk** [comment]
@khanjerry chmod +x /bin/badbodF/BadMod.php

**Comment by MrSqar-Ye** [comment]
sudo chmod +x /bin/BadMod && sudo chmod +x /bin/badmod && sudo chmod +x /bin/badmodF/*

**Comment by Techlord210** [comment]
@Endt4sk it show this
![image](https://user-images.githubusercontent.com/86418442/140064511-33f6a99b-21e4-49d8-8364-c6d0cf8ecec0.png)
there is no file or location??
